Repository minddonyy/AlgorithmStudy, pull requests merged in 2025-08, with the labels that each got.

#119 [Solve] : [BOJ] 23082 균형 삼진법 - 문제 해결
  minwoo/BOJ/23082/sol.cpp
Labels: 해결, 민우

#172 [Solved] : BOJ21944 문제 추천 시스템 Version 2 문제 해결
  Comet/BOJ/21944/소스.cpp
Labels: 해결, 혜성

#152 [Solve]: [BOJ] 1744 수 묶기 - 문제해결
  sangGyenog/BOJ/1744/sol.java
Labels: 해결, 상경

#171 [Solved] : BOJ/21939 문제 추천시스템 Version 1 문제 해결
  Comet/BOJ/21939/소스.cpp
Labels: 해결, 혜성

#170 [Solved] : BOJ/21610 마법사 상어와 비바라기 문제 해결
  Comet/BOJ/21610/소스.cpp
Labels: 해결, 혜성

#161 [Solve]: [BOJ] 5557 1학년 - 문제해결
  sangGyenog/BOJ/5557/sol.java
Labels: 해결, 상경

#160 [Solved] : BOJ/19236 청소년 상어 문제 풀이
  Comet/BOJ/19236/sol.cpp
Labels: 해결, 혜성

#143 [Solve] : [BOJ] 2668 숫자고르기 - 문제 해결
  minwoo/BOJ/2668/sol.cpp
Labels: 해결, 민우

#154 [solved] : BOJ/2169 로봇 조종하기 문제 해결
  Comet/BOJ/2169/소스.cpp
Labels: 해결, 혜성

#139 [Solved] : BOJ/2668 숫자고르기 문제 해결
  Comet/BOJ/2668/sol.cpp
Labels: 해결, 혜성

#149 [Solve]: [BOJ] 11931 수 정렬하기 4 - 문제해결
  sangGyenog/BOJ/11931/sol.java
Labels: 해결, 상경

#141 [Solve]: [BOJ] 2668 숫자고르기 - 문제해결
  sangGyenog/BOJ/2668/sol.py
Labels: 해결, 상경

#137 [Solve]: [BOJ] 3049 다각형의 대각선 - 문제해결
  sangGyenog/BOJ/3049/sol.java
Labels: 해결, 상경

#145 [Solved] : BOJ/1504 특정한 최단 경로 문제 해결
  Comet/BOJ/1504/소스.cpp
Labels: 해결, 혜성

#144 [Solved] : Pgm/12979 기지국 설치 문제 해결
  Comet/Programmers/12979/sol.cpp
Labels: 해결, 혜성

#147 [Solved] : BOJ/1238 파티 문제 해결
  Comet/BOJ/1238/소스.cpp
Labels: 해결, 혜성

#140 [Solved] : BOJ/2056 작업 문제 해결
  Comet/BOJ/2056/소스.cpp
Labels: 해결, 혜성

#134 [Solve]: [BOJ] 20058 마법사 상어와 파이어스톰 - 문제해결
  sangGyenog/BOJ/20058/sol.java
Labels: 해결, 상경

#120 [Solved] : BOJ/1759 암호 만들기 문제 해결
  Comet/BOJ/1759/소스.cpp
Labels: 해결, 혜성

#121 [Solve] : [BOJ] 11931 수 정렬하기 - 문제 해결
  minwoo/BOJ/11931/sol.cpp
Labels: 해결, 민우

#122 [Solve]: [BOJ] 16235 나무재테크 - 문제해결
  sangGyenog/BOJ/16235/sol.java
Labels: 해결, 상경

#131 [Solve]: [BOJ] 12919 A와 B 2 - 문제해결
  sangGyenog/BOJ/12919/sol.java
Labels: 해결, 상경

#128 [Solve]: [BOJ] 9372 상근이의 여행 - 문제해결
  sangGyenog/BOJ/9372/sol.java
Labels: 해결, 상경

#129 [Solved] : BOJ/12919 A와 B 2 문제 해결
  Comet/BOJ/12919/sol.cpp
Labels: 해결, 혜성

#133 [Solve] : [BOJ] 20058 마법사 상어와 파이어스톰 - 문제 해결
  minwoo/BOJ/20058/sol.cpp
Labels: 해결, 민우
